// Instance View
export const FETCH_INSTANCE_STARTED = 'FETCH_INSTANCE_STARTED'
export const FETCH_INSTANCE_FULFILLED = 'FETCH_INSTANCE_FULFILLED'
export const INSTANCE_LINKS_ADDED = 'INSTANCE_LINKS_ADDED'
export const FETCH_INSTANCE_FAILED = 'FETCH_INSTANCE_FAILED'

// List Fetching
export const FETCH_LIST_FAILED = 'FETCH_LIST_FAILED'

// Loading Stuff
export const REQUEST_MADE = 'REQUEST_MADE'
export const REQUEST_RESOLVED = 'REQUEST_RESOLVED'
