export enum HTTP_STATUS_TYPE_KEYS {
  OK = 'OK', // 👍
  BAD_REQUEST = 'BAD_REQUEST',
  FORBIDDEN = 'FORBIDDEN',
  UNAUTHORIZED = 'UNAUTHORIZED',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
}

export const HTTP_STATUSES: {
  [key: string]: { type: string; code: number };
} = {
  [HTTP_STATUS_TYPE_KEYS.OK]: { type: HTTP_STATUS_TYPE_KEYS.OK, code: 200 }, // 👍
  [HTTP_STATUS_TYPE_KEYS.BAD_REQUEST]: {
    type: HTTP_STATUS_TYPE_KEYS.BAD_REQUEST,
    code: 400,
  },
  [HTTP_STATUS_TYPE_KEYS.FORBIDDEN]: {
    type: HTTP_STATUS_TYPE_KEYS.FORBIDDEN,
    code: 403,
  },
  [HTTP_STATUS_TYPE_KEYS.UNAUTHORIZED]: {
    type: HTTP_STATUS_TYPE_KEYS.UNAUTHORIZED,
    code: 401,
  },
  [HTTP_STATUS_TYPE_KEYS.NOT_FOUND]: {
    type: HTTP_STATUS_TYPE_KEYS.NOT_FOUND,
    code: 404,
  },
  [HTTP_STATUS_TYPE_KEYS.INTERNAL_SERVER_ERROR]: {
    type: HTTP_STATUS_TYPE_KEYS.INTERNAL_SERVER_ERROR,
    code: 500,
  },
  [HTTP_STATUS_TYPE_KEYS.SERVICE_UNAVAILABLE]: {
    type: HTTP_STATUS_TYPE_KEYS.SERVICE_UNAVAILABLE,
    code: 503,
  },
};
