version: '3.3'
services:
  cypress:
    image: 'cypress/included:cypress-12.13.0-node-18.16.0-chrome-113.0.5672.92-1-ff-113.0-edge-113.0.1774.35-1'
    depends_on:
      - fusion
      - delta
    environment:
      - CYPRESS_NEXUS_API_URL=http://delta.test:8098/v1
      # - CYPRESS_BASE_URL=http://fusion.test:8000

    working_dir: /e2e
    container_name: cypress
    entrypoint: ['bash']
    stdin_open: true
    tty: true
  fusion:
    depends_on:
      - delta
    environment:
      ANALYSIS_PLUGIN_SHOW_ON_TYPES: 'Analysis,DetailedCircuit,AnalysisReport,Report'
      API_ENDPOINT: 'http://delta.test:8098/v1'
      CLIENT_ID: 'fusion'
    volumes:
      - ../:/opt/nexus
    image: nexus-web:fresh
    expose:
      - 8000
    ports:
      - 8000:8000
    networks:
      default:
        aliases:
          - fusion.test
  delta:
    depends_on:
      - keycloak
      - elasticsearch
      - blazegraph
      - postgres
    environment:
      DELTA_PLUGINS: '/opt/docker/plugins/'
      DELTA_EXTERNAL_CONF: '/config/delta-postgres.conf'
      KAMON_ENABLED: 'false'
    image: bluebrain/nexus-delta:1.8.0-M8
    entrypoint:
      [
        'bin/wait-for-it.sh',
        '-s',
        '-t',
        '0',
        'postgres:5432',
        '--',
        'bin/wait-for-it.sh',
        '-s',
        '-t',
        '0',
        'elasticsearch:9200',
        '--',
        './bin/delta-app',
        '-Xmx4G',
        '-Dapp.cluster.remote-interface=delta',
        '-Dapp.http.port=8098',
      ]
    expose:
      - 8098
    ports:
      - 8098:8098
    volumes:
      - ./config:/config
      - /tmp:/default-volume
    networks:
      default:
        aliases:
          - delta.test
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    environment:
      KEYCLOAK_ADMIN: 'admin'
      KEYCLOAK_ADMIN_PASSWORD: 'admin'
      DB_VENDOR: H2
    command:
      - start-dev
      - --http-port=8080
      - --hostname=keycloak.test
      - --hostname-port=8080
      - --hostname-strict=false
      - --hostname-strict-backchannel=false
      - --log-level=DEBUG
    ports:
      - 8080:8080
    networks:
      default:
        aliases:
          - keycloak.test
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      ES_JAVA_OPTS: '-Xmx4G'
      discovery.type: 'single-node'
      bootstrap.memory_lock: 'true'
      ELASTIC_PASSWORD: 'password'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9200/_cluster/health']
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - 9200:9200

  blazegraph:
    image: bluebrain/blazegraph-nexus:2.1.6-RC
    environment:
      JAVA_OPTS: '-Djava.awt.headless=true -XX:MaxDirectMemorySize=300m -Xms4g -Xmx4g -XX:+UseG1GC'
    ports:
      - 9999:9999

  postgres:
    image: library/postgres:15.1
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
