name: Migration
on:
  push:
    branches:
      - fusion-react-18-vite

jobs:
  publish-preview:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build
        run: |
          docker build -t bluebrain/nexus-web:migrate .
      - name: Publish To DockerHub
        run: |
          echo ${{ secrets.DOCKER_PASS }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
          docker push bluebrain/nexus-web:migrate

