name: Preview
on:
  push:
    branches:
      - develop

jobs:
  publish-snapshot:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        run: |
          docker build -t bluebrain/nexus-web-preview:latest .
      - name: Publish To DockerHub
        run: |
          echo ${{ secrets.DOCKER_PASS }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
          docker push bluebrain/nexus-web-preview:latest