name: Release
on:
  release:
    types: [ published ]

jobs:
  release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        run: |
          VERSION=`echo "${{ github.ref_name }}" | 's/^v//gi'`
          docker build -t bluebrain/nexus-web:$VERSION .
      - name: Publish To DockerHub
        run: |
          VERSION=`echo "${{ github.ref_name }}" | 's/^v//gi'`
          echo ${{ secrets.DOCKER_PASS }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
          docker push bluebrain/nexus-web:$VERSION