# TODO Remove this test GH Action again after debugging
name: E2E Tests

on: [pull_request]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Docker image
        run: docker build . --tag=nexus-web:fresh

      - name: Start services
        run: docker-compose -f ci/docker-compose.yml up -d && sleep 60

      - name: Copy nexus-web into Cypress container
        run: docker cp ./. cypress:/e2e

      - name: Run e2e tests
        run: >-
          echo | timeout --verbose 20m docker exec
          -e 'DEBUG=cypress:launcher:browsers NODE_TLS_REJECT_UNAUTHORIZED=0'
          -t
          cypress
          cypress run
          --headless
          --config-file cypress.config.ts
          --browser chrome
          --record
          --key ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Cleanup Docker Containers
        if: always()
        run: docker-compose -f ci/docker-compose.yml down --rmi "local" --volumes
